[package]
name = "short-bases"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
rand = "0.8.5"
flint-sys = "0.7.1"
bitvec = "1.0.1"
